---
ports:
  http: ":8080"
  https: ":8443"
paths:
  assets: "./assets"
  templates: "./assets/views"
  partials: "./assets/views/partials"

# Each key vaue pair represents the root url e.g. host.com/js
# and the root-relative location on disk.
static_routes:
  /js: "static"
  /css: "static"
  /components: "static"
  /img: "static"

ssl:
  host: "ssl.bursa.io"
  allowed_hosts:
    - "bursa.io"
    - "blog.bursa.io"
    - "ssl.bursa.io"
app:
  login_url: "/login"

email:
  mailchimp_key: "4df049b873c7e2d5d08416ecfac6eee4-us9"
  list_id: "ddb450e3b1"
  enabled: false

bitcoin:
  HttpPostMode: true
  DisableTLS: true
  Host: localhost:18332
  User: bitcoinrpc
  Pass: D7YKqDXM5nuhHhAn6xkiMYaapiDfBKzHwCUfLFbVNZkK

logging:
  mode: "dev"
